services:
  backend:
    image: cueclubprojectressources-d0ckeqfyhwbfb6b5.azurecr.io/backend:latest
    build:
      context: ./CueClub-BackEnd
      dockerfile: Dockerfile
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=core_project.settings
      - DATABASE_HOST=admincueclub.database.windows.net
      - DATABASE_NAME=cueclubdb
      - DATABASE_USER=admincueclub
      - DATABASE_PASSWORD=CueClub@2026!
      - DATABASE_PORT=1433
    ports:
      - "8000:8000"
    volumes:
      - ./CueClub-BackEnd/uploads:/app/uploads

  frontend:
    image: cueclubprojectressources-d0ckeqfyhwbfb6b5.azurecr.io/frontend:latest
    build:
      context: ./CueClub-FrontEnd
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DEBUG=True
    depends_on:
      - backend
